name: Notify Code Path Changes

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**'

env:
  EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
  EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
  GITHUB_REPOSITORY: ${{ github.repository }}
  GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js (if using JavaScript/Node.js script)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install axios

      - name: Run Notification Script
        run: |
          node test/send-notification-on-change.js
          chmod +x test/send_notification_on_change.sh
          ./test/send_notification_on_change.sh
