name: Find stale PRs

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 9 * * *'

jobs:
  fetch-PRs:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch pull requests
        id: local
        uses: paritytech/stale-pr-finder@main
        with:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.27.1
        with:
          channel-id: 'github-action-test'
          slack-message: "Stale PRs in sourcecred repo: \n$LOCAL_PR"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          LOCAL_PR: ${{ steps.local.outputs.message }}"
